### ISSUE TITLE
Identificatie van begrippenkaders

### ISSUE THREAD

**Issue by importalis** [dataoverheid/dcat-ap-donl#1]
We willen datasets en dataservices graag verrijken met begrippen die afkomstig zijn uit bestaande begrippenkaders. Zie bijvoorbeeld https://begrippenxl.nl/nl/. Om wildgroei te voorkomen, willen we vooraf vaststellen welke begrippenkaders we op data.overheid.nl willen gebruiken. Op deze manier kunnen we ook nagaan of een toegekend begrip "geldig" is. Hierbij controleren we of het toegekende begrip voorkomt in een van de toegestane begrippenkaders.

Deze toegekende begrippen willen we ook graag kunnen uitwisselen. Dit betekent dat ze onderdeel moeten worden van het toepassingsprofiel voor DCART2.

De vragen:
1. Hoe gaan we in het DCAT-model aangeven welke begrippenkaders zijn toegestaan?
2. Is het noodzakelijk om een nieuwe property aan te maken voor begrippen? Standaard biedt DCAT property dcat:theme. Deze gebruikt data.overheid.nl nu om een thema uit de taxonomie beleidsagenda toe te kennen aan een dataset. Deze is verplicht. Het lijkt praktisch om een optionele property "donl:begrip" toe te voegen waarin optionele begrippen kunnen worden vastgelegd.

**Comment by keestrautwein** [comment]
We hebben een aantal zaken afgesproken:
1. We inderdaad dcat:theme om te verwijzen naar bestaande begrippenkaders. Punt van aandacht is dat een Theme alleen kan verwijzen naar een skos:Concept uit een skos:ConceptSchema. Als een begrippenkader anders is gestructureerd, kan het niet in Theme worden opgenomen
2. het is toegestaan meerdere dcat:Themes op te nemen; Eentje daarvan is verplicht.
3. We willen de EU-MDR waardelijst niet direct opnemen omdat we in Nederland de Taxonomie Beleidsagenda lijst hebben. Het wordt voor gebruikers verplicht daar een waarde uit te kiezen
4. We maken een mapping van de Taxonomie Beleidsagenda naar de EU-MDR waardelijst. Op die manier is het DONL profiel te mappen op dat van de EU;
5. We gebruiken de Taxonomie Beleidsagenda lijst en nog niet de TOP lijst van TOOI omdat 1. de Taxonomie Beleidsagenda nu al gebruikt wordt; 2. Een migratiepad van de Taxonomie Beleidsagenda naar de TOP lijst ons nog niet bekend is; 3. Omdat de status van TOOI op de langere termijn nog niet gewaarborgd lijkt;
6. Voor andere waardes van Theme geven we de voorkeur aan een vastgestelde lijst, die voor heel Nederland geldt of die geldt binnen een bepaald domein;
7. Domein-specifieke lijsten 
8. We raden het gebruik waardelijsten in Theme af, als die waarde in een andere data:property wordt opgeslagen. Met name de Overheidsorganisatie waardelijst hoort niet in Theme thuis. Betrokken organisaties willen we opslaan met de rol die zij spelen, Standaard zijn daarvoor  dct:creator en dct:publisher beschikbaar. Andere rollen met uitvoerende organisatie kunnen worden toegevoegd met [dcat:Relationship](http://www.w3.org/ns/dcat#Relationship) en [dcat:hadRole](http://www.w3.org/ns/dcat#hadRole). 
9. Als een gebruiker een eigen thema-lijst wil gebruiken kan die worden toegevoegd m.b.v. ThemeTaxonomy in een catalogus;
10. Een waardelijst die we in het DONL profiel willen ondersteunen is sc:Clusterbegrippen
11. Andere lijsten zijn ook mogelijk: gebruikers kunnen deze waardes gebruiken in hun DCAT catalogus. De waardes worden wel door DONL opgeslagen, maar zijn niet per sé beschikbaar in de UI. Bij de ontwikkeling van DONL moet per thema gekeken worden of het ondersteund kan worden in de UI van de applicatie. De gegevens zijn echter wel beschikbaar. 
6. Domein-specifieke lijsten laten we aan gebruikers over. Ze kunnen in een later stadium door de applicatie ondersteund worden.
12. We kunnen nog op https://begrippenxl.nl/nl/ of https://op.europa.eu/ga/web/eu-vocabularies/controlled-vocabularies kijken of er interessante lijsten zijn die we kunnen aanraden;

Twee dingen te doen:
1. mapping van Taxonomie Beleidsagenda naar EU MDR lijst;
2. Onderzoeken of er nog interessante waardelijsten beschikbaar zijn op https://begrippenxl.nl/nl/ of https://op.europa.eu/ga/web/eu-vocabularies/controlled-vocabularies;

**Comment by keestrautwein** [comment]
Onderzoek gedaan naar de waardelijsten: we gaan ze niet opnemen in thema's, maar het bestaan van de EU lijsten gaan we wel in een tekst noemen.

**Comment by keestrautwein** [comment]
Voor de mapping van de Taxonomie Beleidsagenda naar de EU MDR lijst maken we een nieuwe issue.
