### ISSUE TITLE
checksum

### ISSUE THREAD

**Issue by keestrautwein** [dataoverheid/dcat-ap-donl#10]
Openstaande vraag: hoe ziet de vulling van checksum er precies uit? Ik zou verwachten dat behalve de waarde van de checksum ook het gebruikte hash-alogoritme om de waarde mee te berekenen wordt meegestuurd.

**Comment by WterBerg** [comment]
https://github.com/SEMICeu/DCAT-AP/issues/158

**Comment by CasperKoop** [comment]
DCAT AP 2.1 lijkt in de eigen documentatie niet altijd consequent te zijn, maar het huidige ontwerp is het volgende:

Mandatory properties for Checksum:
|Property | URI| Range|
|----------|--------------|-------|
|algorithm | spdx:algorithm| http://spdx.org/rdf/terms#ChecksumAlgorithm|
|checksum value | spdx:checksumValue| Rdfs:Literal typed as xsd:hexBinary|

Daarmee voldoet het ontwerp aan de verwachting van Kees.
