### ISSUE TITLE
Verschillende talen

### ISSUE THREAD

**Issue by importalis** [dataoverheid/dcat-ap-donl#11]
De W3C maakt het mogelijk om de metadata zoals titel en beschrijving vast te leggen in verschillende talen. Op data.overheid.nl is  nu maximaal een taal mogelijk.

Daarnaast is het mogelijk om de taal aan te geven van de dataset zelf.

De EU biedt ook de mogelijkheid om daarnaast ook apart de taal van de distributie aan te geven.

Wat is hier precies gewenst?

**Comment by importalis** [comment]
W3C specificeert dct:language als eigenschap in de superklasse `Cataloged Resource`. DCAT-AP-EU specificeert deze eigenschap voor `Cataloged Resource` en `Distribution`. De definities verschillen ook:

** DCAT-AP-EU**

This property refers to a language of the Dataset.

**W3C**

A language of the item. This refers to the natural language used for textual metadata (i.e. titles, descriptions, etc) of a cataloged resource (i.e. dataset or service) or the textual values of a dataset distribution. 

Vreemd genoeg staat bij de Usage note: If representations of a dataset are available for each language separately, define an instance of dcat:Distribution for each language and describe the specific language of each distribution using dct:language (i.e. the dataset will have multiple dct:language values and each distribution will have just one as the value of its dct:language property).

W3C lijkt ervan uit te gaan dat de taal van de metadata gelijk is aan de taal van de gegevens in de dataset.

Is dit een juiste aanname?

**Comment by CasperKoop** [comment]
Feedback van Huub:
Je kan de taal ook aangeven met een taal tag bijv @en

**Comment by WterBerg** [comment]
Voorstel:

Metadata is altijd in __maximaal een__ taal geschreven. Het ondersteunen van meerdere talen per object maakt het geheel onnodig complex. Bij data.overheid.nl is in de afgelopen zeven jaar nog nooit de wens uitgesproken om dit mogelijk te maken, er lijkt dus ook (in Nederland) geen behoefte te zijn om dit wel te kunnen.

Hoe dit qua implementatie eruit ziet is buiten de scope van de standaard zelf, maar ik kan me voorstellen dat je dat op een van onderstaande manieren doet:

- Systeem voert een controle uit of alle attributen een language tag hebben en dat deze voor elk attribuut hetzelfde is. "Alle literal velden bevatten een `@en` tag? Dit metadataobject is in het Engels omschreven."
- Systeem biedt ondersteuning voor een extra veld, bv. "metadataLanguage" waarin wordt aangegeven wat de taal is van alle andere meegestuurde literal velden (dit is hoe data.overheid.nl het momenteel doet; het "metadataLanguage" veld heeft een range van [DONL:Language](https://waardelijsten.dcat-ap-donl.nl/donl_language.json)).

---

Daarnaast zou ik voorstellen dat de metadata taal van een `dcat:Distribution` altijd overeen moet komen met de metadata taal van de bovenliggende `dcat:Dataset`.

**Comment by CasperKoop** [comment]
Ter aanvulling aan het gebruik van de languagetag. DCAT-AP 2.1 Hoofdstuk 8 geeft een uitgebreide beschrijving over het gebruik van language tags. Voor donl wordt dit erg uitgebreid. In overeenstemming met de EU worden de volgende talen ondersteund:

| Taal       | Tag |
|------------|-----|
| Duits      | de  |
| Engels     | en  |
| Fries      | fy  |
| Nederlands | nl  |

Deze waardes komen overeen met [ISO 639-1](https://nl.wikipedia.org/wiki/Lijst_van_ISO_639-codes) en de [IANA lijst van language tags](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry)
