### ISSUE TITLE
Wat te doen met `distribution type` in Distribution?

### ISSUE THREAD

**Issue by importalis** [dataoverheid/dcat-ap-donl#12]
Deze lijkt achterhaald. Klopt dat?

**Comment by importalis** [comment]
Dit gegeven is nu specifiek voor data.overheid.nl.
Zie https://github.com/dataoverheid/dcat-ap-donl/wiki/Distribution#property-distribution-type

**Comment by importalis** [comment]
Evt. zou eigenschap dct:conformsTo gebruikt kunnen worden.

**Comment by CasperKoop** [comment]
Als samenvatting van de discussie die zojuist in de werkgroep is gevoerd.
DONL wil inzichten geven over datasets door visualisaties te maken voor datasets en een apart kopje te geven voor documentatie. Omdat dit niet voor elke distributie mogelijk is, is het nodig om aan te kunnen geven dat een distributie op een bepaalde manier geïnterpreteerd kan worden (en dus weergegeven op DONL of andere plek).

In het huidige 'distribution type' worden ook 'downloadbaar bestand' en 'webservice' benoemd, maar dit valt niet onder de benoemde categorie. Daarbij kan de informatie of het om een downloadbaar bestand  of webservice gaat op andere manieren uit de DCAT omschrijving worden gehaald. 

Met het omschreven doel lijkt 'distribution type' niet meer de beste benaming voor de eigenschap, dus over een betere beschrijving wordt nagedacht.

**Comment by CasperKoop** [comment]
Wanneer de types `downloadbaar bestand` en `webservice` niet meer gaan voorkomen in deze functionaliteit blijven `data schema`, `documentatie` en `visualisatie` over. Omdat documentatie beter in het veld `documentation` past hebben we:

- `Data schema`
- `Visualisatie`

Deze type distributies kunnen worden gezien als bijlages bij een dataset om inzicht erin te geven.  

Ik stel voor om alleen de bovenstaande 2 waardes in de waardenlijst te houden en default waarde leeg te houden. De benaming kunnen we veranderen naar bijvoorbeeld `bijlagetype` om te benadrukken dat het niet gaat om de eigenlijke data, maar aanvullende.

**Comment by CasperKoop** [comment]
De naam van deze eigenschap is `supportingRole` geworden. Waardelijst gaat nog komen.
