### ISSUE TITLE
Waarom komen property `spatial resolution` en `temporal resolution` voor in dataset en distributie?

### ISSUE THREAD

**Issue by importalis** [dataoverheid/dcat-ap-donl#13]
Waarom zou je deze gegevens op twee plaatsen willen vastleggen? Alleen bij distributie lijkt voldoende.

**Comment by CasperKoop** [comment]
Op data.overheid.nl ken ik geen voorbeelden, maar wel andere. Voornamelijk uit sensordata of meetdata.

Neem bijvoorbeeld het classificeren van de kwaliteit van wegen (in opdracht van gemeenten). Dat wordt gedaan door over de weg te rijden en geluid- en trilling data te verzamelen.
Deze data kan openbaar gedeeld worden. Zo kunnen bv conclusies uit onderzoeken worden gecontroleerd, maar kan er ook verder onderzoek mee gedaan worden. 
Wanneer alle ruwe data gedeeld zou worden, wordt het snel te groot om aan te bieden. In dat geval kan de dataeigenaar ervoor kiezen om voor de data te presenteren op andere manier.
Zo kan voor geluidshinder de temporal resolution op 1/48000 s (sample frequency van 48kHz) worden gezet in plaats van de hogere frequentie waarmee de meting gedaan is.
Dan ziet men welke data er voor het onderzoek gebruikt is én is er data beschikbaar voor hergebruik. Mochten er toch geïnteresseerden zijn in de ruwe data zijn de eigenschappen in ieder geval bekend. Hoe deze volledige dataset (nieuwe distributie) bij de geïnteresseerde komt kan een passende oplossing bij worden gevonden.

**Comment by CasperKoop** [comment]
Op het moment worden beide velden niet gebruikt. 
Om het profiel overzichtelijk te houden hebben we besloten om deze eigenschappen nog te parkeren. Op die manier kan er, zodra er behoefte is, gekeken worden naar een duidelijke invulling ervan.
