### ISSUE TITLE
Altijd language tag achter een literal zoals Title of Description?

### ISSUE THREAD

**Issue by keestrautwein** [dataoverheid/dcat-ap-donl#15]
Zowel in de values als in de beschrijvende informatie van DCAT kunnen meerdere talen voorkomen. Om dat aan te geven worden zowel dct:language als het language-tag achter een literal gebruikt.
Maar in de praktijk kennen veel datasets slechts 1 taal. Die taal wordt dan met dct:language aangegeven. 
Vraag: Moet in het geva; er slechts 1 taal voorkomt,  de language-tag nog worden toegevoegd aan de literals? Merk op dat een literal met of zonder language-tag een ander type heeft in Linked Data, wat bijvoorbeeld gevolgen heeft voor SPARQL queries. Streven we naar uniformiteit of eenvoud?

**Comment by CasperKoop** [comment]
"We verplichten inderdaad een language tag achter literals. Moet nog wel worden opgenomen in Respec."@NL
