### ISSUE TITLE
In welke gevallen is het nuttig om om een Catalog record aan te maken van iedere wijziging in een Catalog, Dataset of Dataservice?

### ISSUE THREAD

**Issue by keestrautwein** [dataoverheid/dcat-ap-donl#16]
Met het Catalogrecord worden wijzigingen bijgehouden van `Catalog`, `Dataset` en `Dataservice`. Dit kan zowel een wijziging in de gegevens van een Dataservice betreffen, asl een wijzigingen in de DCAT gegevens zelf, zoals de wijzigingen van een titel.
Omdat iedere Catalogrecord een datum van wijziging heeft, kan hierbij een complete administratie van alle wijzigingen op een DCAT resource worden bijgehouden.

De laatste wijziging wordt bij alle classes, zowel in `Catalog`, `Dataset` en `Dataservice` als in `Distribution` met dct:modified bijgehouden.

In welke gevallen is het nuttig om om een Catalog record aan te maken van iedere wijziging?

**Comment by huubvanoers** [comment]
Uit de discussie in de KOOP werkgroep kwamen we tot de conclusie dat het technisch mogelijk is om een lijst met verschillen en versies te maken, maar dat het publiceren van die lijst in de Catalog overbodig  is. Het advies is om de CatalogRecords in DCAT niet te implementeren.

Als je een administratie wil aanleggen voor de administratieve wijzigingen in deDCAT klassen in CatalogRecord, dan 
Let dan op dat het dan om registratie van de wijzigingen gaat en de registratie van gebruik, zoals bij Dataservices, (bijv. de aanroep voor gemeente Zoetermeer of aanroep voor gemeente Groningen).
Een wijziging in de Dataservice is een wijziging in de API aanroep en/of de achterliggende functie.
Eventueel is dan mogelijk als controle: dct:Modified in het CatalogRecord moet gelijk  zijn aan dct:Modified in betreffende DCAT klasse.
