### ISSUE TITLE
Waarvoor kan een catalog gebruikt worden waarin geen Datasets zijn opgenomen?

### ISSUE THREAD

**Issue by keestrautwein** [dataoverheid/dcat-ap-donl#17]
Volgens het DCAT 2 model is het mogelijk om catalogs te creeëren waarin geen Datasets zijn opgenomen. In welke gevallen zouden we dergelijke gegevens willen uitwisselen?

**Comment by WterBerg** [comment]
Ter info: de discussie van DCAT-AP: https://github.com/SEMICeu/DCAT-AP/issues/180

**Comment by keestrautwein** [comment]
DCAT-AP 2.1.0 lijkt de verplichting vervallen dat een Catalog een Dataset moet bevatten, terwijl een Data Service optioneel is. Zowel Dataset asl DataService zijn optioneel. Het wordt afgeraden om lege Catalogs aan te maken of uit te wisselen: er zit minimaal één Dataset of DataService of Catalog in.
