### ISSUE TITLE
Structurering van data schema's

### ISSUE THREAD

**Issue by importalis** [dataoverheid/dcat-ap-donl#2]
Om afnemers van data.overheid.nl - op het portaal - inzicht te verschaffen in de structuur van een distributie van een dataset, bijvoorbeeld in de betekenis van de kolommen in een spreadsheet, willen we graag een data schema opnemen bij de distributie.

De vragen zijn: 
1. Welke kenmerken willen we hierin beschrijven en 
2. Hoe gaan we die kenmerken structureren.

Een mooi voorbeeld hiervan is opgenomen in Data on the Web Best Practices, Best Practice 3: Provide structural metadata, zie https://www.w3.org/TR/dwbp/#StructuralMetadata

Een mogelijk oplossing hiervoor is ISO19110 FeatureCatalog, Geographic information – Methodology for feature cataloguing (iso19110) — GeoNetwork opensource v3.10 GeoNetwork Documentation (geonetwork-opensource.org), zie https://www.geonetwork-opensource.org/manuals/3.10.x/en/annexes/standards/iso19110.html

**Comment by CelineJansen** [comment]
Voor wat betreft de kenmerken: Wij (Gemeente Eindhoven) hebben in dit kader deelgenomen aan een pilot met Data.Overheid (jullie zijn hier waarschijnlijk wel van op de hoogte, maar voor de volledigheid: https://datacommunities.nl/groups/pilots-betere-data-vindbaarheid). Op ons portaal (leverancier: Opendatasoft) zijn de volgende attributen opgenomen om inzicht te bieden in dataset schema's: 
![image](https://user-images.githubusercontent.com/79267472/139810661-7e4449b2-21b2-43d9-9b69-0be5866a5e88.png). Wat ons betreft zijn vooral een vrije omschrijving en een voorbeeldwaarde interessant. Een richtlijn voor mogelijke onderdelen van de vrije omschrijving gebaseerd op onze bevindingen gedurende de pilot staat in de bijlage.
[Data.Overheid Pilot Eindhoven Bevindingen.pdf](https://github.com/dataoverheid/dcat-ap-donl/files/7459000/Data.Overheid.Pilot.Eindhoven.Bevindingen.pdf)

**Comment by keestrautwein** [comment]
Dit onderwerp is een aantal keer besproken. Er is besloten dit onderwerp nu nog niet in de standaard op te nemen, maar met nadruk de optie open te houden dat op een later tijdstip te doen.
Verder bestaan er voorstellen om tabulatie gegevens te beschrijven aan de hand van de labels van tabellen, kollomen en rijen, behalve bovenstaande link is er ook https://www.w3.org/TR/tabular-data-model/. 
Het ontbreekt echter aan ideeën om dit soort inhoudelijke extra inhoudelijke informatie ook aan andere gegevensoorten mee te geven, zoals een tekst of een afbeelding. Bij dat soort gegevens zou wel een beschrijving meegeleverd kunnen worden, maar op dit moment is niet duidelijk hoe die gemaakt kan worden, terwijl veel tubulaire data de labels van de gegevens gewoon bevat.
Omdat er veel tabuiaire data wordt uitgewisseld, lijkt het toch interessant hier in de toekomst aandacht aan te besteden.
