### ISSUE TITLE
Wat is een catalogus in DCAT nu precies

### ISSUE THREAD

**Issue by CasperKoop** [dataoverheid/dcat-ap-donl#21]
Er lijkt onduidelijkheid te zijn rondom de definitie van [dcat:Catalog](https://www.w3.org/TR/vocab-dcat-2/#Class:Catalog). Wat is het precies en wanneer wordt het gebruikt?

- Wanneer is een catalogus een [dcat:Catalog](https://www.w3.org/TR/vocab-dcat-2/#Class:Catalog)?
- Wanneer is een catalogus een [dcat:Dataset](https://www.w3.org/TR/vocab-dcat-2/#Class:Dataset)?

**Comment by GeraldGrootRoessink** [comment]
Zowel dcat 2 als dcat 3 hanteren deze definitie:

[dcat:Catalog](https://www.w3.org/TR/vocab-dcat-3/#Class:Catalog) represents a catalog, which is a dataset in which each individual item is a metadata record describing some resource; the scope of dcat:Catalog is collections of metadata about datasets or data services.

Hier is een DMBOK wijsheid van toepassing: Met metagegevens moet je in de dagelijkse prakrtijk omgaan zoals je omgaat  met "gewone" gegevens zijn. Dit vergt dat processen worden ingericht om ze in te winnen, in stand te houden en ze ter beschikking te stellen.  De inhoud van dit metadataregister bestaat uit instantie die de verschillende datasets/distributies en dataservices beschrijven. 

Dus elke dcat:Catalog is per definitie een dcat:Dataset.  Dat is tevens de betekenis van de generalisatie-relaties in de modelfiguur in de standaard. 

Wel jammer dat de standaard niet voorziet de catalogus te ontsluiten door middel van een  dcat:Dataservice. Dat kunnen we namelijk heel goed.
