### ISSUE TITLE
Gebruik ID's

### ISSUE THREAD

**Issue by CasperKoop** [dataoverheid/dcat-ap-donl#24]
Dit wordt nog besproken binnen [Europa](https://joinup.ec.europa.eu/collection/semantic-interoperability-community-semic/event/dcat-ap-webinar-26th-april-1500-cet)

**Comment by WterBerg** [comment]
https://dcat-ap-donl.readthedocs.io/en/latest/workflow.html#dataset-identifier

**Comment by CasperKoop** [comment]
In de EU is er [discussie gaande over `amds:identifier`](https://github.com/SEMICeu/DCAT-AP/blob/2.x.y-draft/releases/2.x.y/usageguide-identifiers.md)  Het voorstel is om de identifier die door de dataeigenaar gegeven wordt aan  een dataset te behouden in `dct:identifier` en eventuele andere identifiers in `adms:identifier`  op te nemen. Daarin wordt dan naast de waarde van de identifier zelf ook aan toegevoegd wie deze toevoeging gedaan heeft. Bijvoorbeeld in `dct:creator`

**Comment by CasperKoop** [comment]
<html>
<body>
<p style="margin: 1em 0px; color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">De verplichte eigenschap<span> </span><a href="https://dataoverheid.github.io/dcat-ap-donl/#dct-identifier" style="color: var(--a-normal-text); text-decoration-color: var(--a-normal-underline); text-decoration-skip-ink: none;"><code style="font-family: Menlo, Consolas, &quot;DejaVu Sans Mono&quot;, Monaco, monospace; font-size: 0.9em; hyphens: none; text-transform: none; text-align: start; font-variant: normal; orphans: 3; widows: 3; break-before: avoid;">dct:identifier</code></a><span> </span>bevat de unieke identificatie van de dataset die de data-eigenaar heeft uitgegeven. Deze eigenschap bevat evt. andere unieke identifiers van de dataset zoals gegeven door catalogi als<span> </span><cite><a data-cite="DONL" data-matched-text="[[[DONL]]]" href="https://data.overheid.nl/" style="color: var(--a-normal-text); text-decoration-color: var(--a-normal-underline); text-decoration-skip-ink: none;">data.overheid.nl</a></cite>.</p><p style="margin: 1em 0px; color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">In de<span> </span><code style="font-family: Menlo, Consolas, &quot;DejaVu Sans Mono&quot;, Monaco, monospace; font-size: 0.9em; hyphens: none; text-transform: none; text-align: start; font-variant: normal; orphans: 3; widows: 3; break-before: avoid;">adms:identifier</code><span> </span>wordt de identifier benoemd in<span> </span><code style="font-family: Menlo, Consolas, &quot;DejaVu Sans Mono&quot;, Monaco, monospace; font-size: 0.9em; hyphens: none; text-transform: none; text-align: start; font-variant: normal; orphans: 3; widows: 3; break-before: avoid;">skos:notation</code><span> </span>en de uitgever van de identifier in<span> </span><code style="font-family: Menlo, Consolas, &quot;DejaVu Sans Mono&quot;, Monaco, monospace; font-size: 0.9em; hyphens: none; text-transform: none; text-align: start; font-variant: normal; orphans: 3; widows: 3; break-before: avoid;">dct:creator</code>.</p><p style="margin: 1em 0px; color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Let op, een resource wordt na het aanmaken niet aangepast door anderen met deze other identifier als uitzondering. Een other identifier kan worden toegevoegd als verrijking van de dcat informatie. Voor een voorbeeld zie<span> </span><a href="https://dataoverheid.github.io/dcat-ap-donl/#example-other-identifier" style="color: var(--a-normal-text); text-decoration-color: var(--a-normal-underline); text-decoration-skip-ink: none;">#Other identifier</a></p>

Definitie | Waarde
-- | --
RDF Eigenschap | adms:identifier
Bereik | adms:Identifier
Kardinaliteit | 0..n
Gebruik | Optional


</body>
</html>
