### ISSUE TITLE
Contactpunt toevoegen aan Distributie?

### ISSUE THREAD

**Issue by huubvanoers** [dataoverheid/dcat-ap-donl#32]
Het kenmerk contactpunt (vCard, minimaal e-mail adres) is via Resource gekoppeld aan Catalog, Dataset en Dataservice.
Mogelijk is het voor de ketens zinvol om ook een contactpunt op te geven bij de Distributies. Maar ook zouden de bestaande  contactpunt al voldoende zijn.

**Comment by CasperKoop** [comment]
Bij DONL krijgen we geen vragen binnen over het contactpunt van aparte distributies, tot dusver lijken de vragen op te lossen door te verwijzen naar het contactpunt in de bovenliggende dataset. Mocht deze behoefte toch kenbaar worden kunnen we altijd kijken of dit later toe te voegen is.
