### ISSUE TITLE
Link bij property "Availability" in Distribution lijkt stuk

### ISSUE THREAD

**Issue by keestrautwein** [dataoverheid/dcat-ap-donl#36]
Ik denk dat deze link http://publications.europa.eu/resource/authority/planned-availability moet zijn ipv het huidige http://data.europa.eu/r5r/availability/1.0

**Comment by CasperKoop** [comment]
https://gitcdn.link/cdn/dataoverheid/dcat-ap-donl/main/respec/index.html#Property:distribution_availability

**Comment by CasperKoop** [comment]
Is aangepast
