### ISSUE TITLE
Property: update/modification date in Distributie: Verplicht of Aanbevolen?

### ISSUE THREAD

**Issue by keestrautwein** [dataoverheid/dcat-ap-donl#4]
Het "update/modification date" veld is belangrijk om de kwaliteit van de aangeboden distributie te kunnen inschatten: Een oude dataset heeft minder waarde dan een nieuwere. Ook kan deze eigenschap niet worden afgeleid.
Dus het lijkt passend om op zijn minst deze property "aanbevolen" te maken.
Maar zijn er bezwaren om de property verplicht te maken? Zou dat leiden tot uitvak van datasets? Uitval lijkt op te lossen met een beschrijving hoe het veld in te vullen als de distributie er geen waarde voor heeft.

**Comment by CelineJansen** [comment]
Aanbevolen lijkt me beter dan verplicht. Binnen ons portaal kan de verversing van data automatisch worden afgeleid, maar als je die optie niet hebt is het bijhouden van zo'n veld best een klus. Als zoiets verplicht wordt zijn bepaalde eisen ook belangrijk: kijken we zuiver naar updates binnen de data, of nemen we ook updates van metadata mee. En wat doen we met data die gepland is om eens in de zoveel tijd te verversen is, dan draait er bijvoorbeeld elke week een script om de brondata binnen de halen en te verwerken en zou je zeggen dat elke week de modification date ook ververst kan worden. Maar wat als de brondata niet gewijzigd is? Dan is het lastig om te controleren of er daadwerkelijk sprake is van wijzigingen, of dat er alleen sprake is van verversing. 

![image](https://user-images.githubusercontent.com/79267472/139814170-873fa907-3374-41fc-96ac-a094c317a6ea.png) 

Overigens wel een nuance: historische data kan natuurlijk ook van waarde zijn, en een data met een recente modification date die daarna 3 jaar niet wordt bijgehouden waar dat wel zou moeten / kunnen is ook niet echt meer van waarde. Dus wat dat betreft zegt een opzichzelfstaande modification date nog niet alles. Een update frequentie van data in combinatie met een modification date zegt dan meer.

**Comment by importalis** [comment]
De definitie is gewijzigd in:

> Deze eigenschap bevat de datum waarop de data-eigenaar de gegevens van de distributie voor het laatst heeft gewijzigd. Dat geldt zowel voor een wijziging van de inhoud van de distributie als in de metadata van de distributie.

Zie
https://github.com/dataoverheid/dcat-ap-donl/wiki/Distribution#property-updatemodification-date

Ook is eigenschap dct:modified "Aanbevolen" gemaakt.

**Comment by CasperKoop** [comment]
Ter extra verduidelijking: [release date](https://gitcdn.link/cdn/dataoverheid/dcat-ap-donl/main/respec/index.html#Property:distribution_release_date) / [update/modification date](https://gitcdn.link/cdn/dataoverheid/dcat-ap-donl/main/respec/index.html#Property:distribution_update_date) date gaat altijd over de data inhoudelijk. Als je changes op de metadata bij wilt houden kun je een catalog record aanmaken. Donl houdt dit niet bij.
