### ISSUE TITLE
missende waardelijsten: 

### ISSUE THREAD

**Issue by Harm-Olthof** [dataoverheid/dcat-ap-donl#53]
ik zie op de volgende waardelijst niet: donl:authority  (wordt aan gerelateerd in dataset -> authority en dataset -> publisher.
Ik mis ook: overheid:grondslag
Waar vind ik deze waardelijst?
Groeten,
Harm Olthof

**Comment by CasperKoop** [comment]
Hallo Harm,

`donl:authority` komt voor in [DCAT-AP-DONL 1.1](https://dcat-ap-donl.readthedocs.io/en/latest/), daarvoor wordt de waardelijst [`DONL:Organization`](https://waardelijsten.dcat-ap-donl.nl/donl_organization.json) gebruikt.
DCAT-AP-DONL 2 heeft dezelfde constructie, alleen gebruiken we in plaats van `donl:authority` nu `dct:creator` (om in lijn te liggen met de bovenliggende profielen). Daarnaast gebruiken we in plaats van `DONL:Organization` nu
[`overheid:Organisatie`](https://standaarden.overheid.nl/owms/terms/Organisatie) en [`donl:RelevantOrganization`](https://raw.githubusercontent.com/dataoverheid/dcat-ap-donl/main/taxonomy/organizations.ttl). Samen bevatten deze dezelfde waardes als het eerdere `DONL:Organization`

`overheid:grondslag` gaat over naar het iets uitgebreidere [`Legal foundation`](https://dataoverheid.github.io/dcat-ap-donl/#donl-LegalFoundation). 

Groeten, Casper

**Comment by Harm-Olthof** [comment]
Hallo @CasperKoop dank voor de informatie en de links naar DCAT-AP-DONL 2.0
Groeten,
Harm
