### ISSUE TITLE
Eigenschap dct:accessRights in Disrtribution

### ISSUE THREAD

**Issue by importalis** [dataoverheid/dcat-ap-donl#6]
W3C specificeert de eigenschappen dct:accessRights zowel voor Distribution als voor Datasets en Dataservices (in superklasse Cataloged Resource). Zie https://www.w3.org/TR/vocab-dcat-2/#Property:distribution_access_rights

DCAT-AP-EU neemt dct:accessRights in Distribution niet over.

Is het zinvol om eigenschap `access rights` zowel in de Dataset als in de Distribution te beschrijven?

**Comment by CasperKoop** [comment]
Er komt een discussie over afgeleide properties

**Comment by huubvanoers** [comment]
Als je een distributie opvat als een representatie van een dataset, dan kan je bij 1 dataset meerdere distributies hebben met verschillende rechten per distributie.
Anderzijds: Een dataset is een afgestemde gegevensverzameling. Als er andere rechten nodig zijn in de gegevensverzameling, dan ontstaat in feite een nieuwe, andere dataset. Dan heb je geen accessRights nodig in Distributie.
Normaliter zouden de rechten in de Distributie(s) gelijk zijn aan de rechten in de Dataset. Je kan het expliciet opnemen bij Distributie, maar is dan optioneel, erft over.

Wat betekent het als rechten op Dataset afwijken van Distributie?
Dat zou alleen mogen als er meerdere Distributies zijn.  De rechten op Distributie gaan dan boven die op de Dataset

Samenvattend: accessRights wel opnemen bij Distribution, maar niet verplicht, maximaal 1 (Card. 1..1).

**Comment by CasperKoop** [comment]
@huubvanoers , klopt de card. van 1 .. 1 hier als het niet verplicht is?

**Comment by huubvanoers** [comment]
Hoi Casper,

Het was even zoeken, maar oorspronkelijk was er een lijst met redenen van gesloten datasets. Dankzij Willem is daar Public, openbaar aan toegevoegd, dus is het de lijst accessrights en is daardoor verplicht en 1 waarde toegestaan, dus 1..1 card en kan je het op verplicht zetten (met default Public).

Groeten,
Huub

Ps, zit nu helemaal in de BIV dataclassificatie.
