### ISSUE TITLE
Is er behoefte aan eigenschappen dcat:compressFormat en dcat:packageFormat in Distribution?

### ISSUE THREAD

**Issue by importalis** [dataoverheid/dcat-ap-donl#9]
Zie
- https://www.w3.org/TR/vocab-dcat-2/#Property:distribution_compression_format
- https://www.w3.org/TR/vocab-dcat-2/#Property:distribution_packaging_format

**Comment by keestrautwein** [comment]
We hebben gekozen voor de eenvoudigste en meest consequente oplossing:
In het DONL profiel worden de velden dcat:packageFormat en dcat:compressFormat niet gebruikt. Onafhankelijk van compressie of "packaging" wordt met dcat:mediaType en dct:format aangegeven wat het formaat is van het aangeboden bestand in de distributie.
ZIe voor details de beantwoordingen van [issue 8](https://github.com/dataoverheid/dcat-ap-donl/issues/8)

**Comment by CasperKoop** [comment]
Zie commentaar van Kees
